import { HeaderBeforeLogin } from "@/components";

export default function Home() {
  return (
    <>
      <HeaderBeforeLogin />
      <div>
        <h1>Reviu.ID</h1>
        <p>Generated by create next app</p>
      </div>
    </>
  );
}
